export const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH
export const URL_AZURE_AD_LOGOUT = process.env.NEXT_PUBLIC_URL_AZURE_AD_LOGOUT
export const URL_REDIRECT_LOGIN = process.env.NEXT_PUBLIC_REDIRECT_LOGIN
export const URL_REDIRECT_MENU = process.env.NEXT_PUBLIC_REDIRECT_MENU

export const {
  AZURE_AD_CLIENT_GRANT_TYPE,
  AZURE_AD_CLIENT_ID,
  AZURE_AD_CLIENT_RESOURCE,
  AZURE_AD_CLIENT_SECRET,
  AZURE_AD_GRAPH_GET_USER_BY_EMAIL,
  AZURE_AD_GRAPH_GROUPS,
  AZURE_AD_GRAPH_URL_TOKEN,
  AZURE_AD_TENANT_ID,
  TIMEOUT_SESSION_MINUTES,
  PREFIX_LOGIN,
  SESSION_TOKEN,
  NODE_ENV,
  ID_FRONT,
} = process.env

export const REFETCH_INTERVAL = 60
